### ISSUE TITLE
Original author for Drupal is wrong

### ISSUE THREAD

**Issue by mikestefanello** [backdrop-contrib/antibot#2]
The original author is the same person who maintains it. Please correct that.

**Comment by jenlampton** [comment]
I've corrected the credits section, I'm so sorry about that. I'm not sure where I got the other name. Would you prefer the link go to your GitHub username, or is your d.o profile okay?

**Comment by mikestefanello** [comment]
I was mostly joking, but if you want to update it, either is fine. Thanks.

**Comment by jenlampton** [comment]
In that case, closing. (Name change has been committed)
